import { getDeliveryAgents } from "../models/deliveryAgentModel.js";
import pool from "../config/db.js"; 
import PDFDocument from "pdfkit";

export const fetchDeliveryAgents = async (req, res) => {
  try {
    const deliveryAgent = await getDeliveryAgents();

    if (!deliveryAgent) {
      return res.status(404).json({ message: "Failed to return Delivery Agents" });
    }

    res.json(deliveryAgent);

  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Server error" });
  }
};

export async function exportUserReport(req, res) {
  try {
    const adminName = req.user?.firstName + " " + req.user?.lastName || "Administrator";

    // Fetch user data with joins
    const query = `
      SELECT 
        u.id, u.first_name, u.last_name, u.email, u.phone, u.provider, u.role,
        u.account_status, u.created_at,
        cp.preferences, cp.address, cp.date_of_birth, cp.gender,
        rp.restaurant_name, rp.cuisine_type,
        da.status AS delivery_status
      FROM users u
      LEFT JOIN customer_profiles cp ON cp.user_id = u.id
      LEFT JOIN restaurant_profiles rp ON rp.user_id = u.id
      LEFT JOIN deliveryagent da ON da.user_id = u.id
      ORDER BY u.created_at ASC
    `;
    const { rows: users } = await pool.query(query);

    // Prepare PDF document
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 60, bottom: 60, left: 60, right: 60 },
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", "attachment; filename=user-report.pdf");

    doc.pipe(res);

    // === Theme colors ===
    const primaryColor = "#065f46";
    const secondaryColor = "#f0fdf4";
    const textDark = "#111827";
    const textMedium = "#4b5563";
    const textLight = "#6b7280";
    const accentColor = "#10b981";
    const pageWidth = doc.page.width;
    const pageHeight = doc.page.height;
    const leftMargin = 60;
    const rightMargin = pageWidth - 60;
    const contentWidth = rightMargin - leftMargin;

    // === Header ===
    doc.rect(0, 0, pageWidth, 100).fill(primaryColor);
    doc.fillColor("white")
      .font("Times-Bold")
      .fontSize(26)
      .text("USER REPORT", leftMargin, 30);
    doc.fontSize(12).font("Times-Roman").text("System User Overview", leftMargin, 60);

    doc.fillColor("white").fontSize(12).text("Generated by: " + adminName, rightMargin - 180, 60);
    doc.fillColor("white").text(new Date().toLocaleString(), rightMargin - 180, 75);

    let currentY = 130;

    // === Summary Section ===
    const totalUsers = users.length;
    const totalCustomers = users.filter((u) => u.role === "customer").length;
    const totalRestaurants = users.filter((u) => u.role === "restaurant").length;
    const totalDelivery = users.filter((u) => u.role === "delivery").length;

    doc.fillColor(textDark).font("Times-Bold").fontSize(16).text("Report Summary", leftMargin, currentY);
    currentY += 25;

    const labelX = leftMargin + 10;
    doc.font("Times-Roman").fontSize(11).fillColor(textMedium)
      .text(`Total Users: ${totalUsers}`, labelX, currentY)
      .text(`Customers: ${totalCustomers}`, labelX + 200, currentY)
      .text(`Restaurants: ${totalRestaurants}`, labelX + 400, currentY);
    currentY += 18;
    doc.text(`Delivery Agents: ${totalDelivery}`, labelX, currentY);
    currentY += 40;

    // === Group by Role ===
    const grouped = {
      customer: users.filter((u) => u.role === "customer"),
      restaurant: users.filter((u) => u.role === "restaurant"),
      delivery: users.filter((u) => u.role === "delivery"),
      admin: users.filter((u) => u.role === "admin"),
    };

    for (const [role, list] of Object.entries(grouped)) {
      if (!list.length) continue;

      // Section Header
      doc.rect(leftMargin, currentY, contentWidth, 35).fill(secondaryColor);
      doc.fillColor(primaryColor).font("Times-Bold").fontSize(14)
        .text(role.toUpperCase() + "S", leftMargin + 10, currentY + 10);
      currentY += 45;

      // Table headers
      const col1 = leftMargin + 10; // Name
      const col2 = leftMargin + 150; // Email
      const col3 = leftMargin + 320; // Phone
      const col4 = leftMargin + 430; // Extra

      doc.fillColor(textMedium).font("Times-Bold").fontSize(10);
      doc.text("Name", col1, currentY);
      doc.text("Email", col2, currentY);
      doc.text("Phone", col3, currentY);
      doc.text("Details", col4, currentY);
      currentY += 18;

      // Divider
      doc.strokeColor("#9ca3af").moveTo(leftMargin, currentY).lineTo(rightMargin, currentY).stroke();
      currentY += 10;

      for (const u of list) {
        if (currentY > pageHeight - 100) {
          doc.addPage();
          currentY = 60;
        }

        const bgColor = list.indexOf(u) % 2 === 0 ? "#ffffff" : "#f9fafb";
        doc.rect(leftMargin, currentY - 5, contentWidth, 22).fill(bgColor);

        const fullName = `${u.first_name || ""} ${u.last_name || ""}`;
        const details =
          role === "customer"
            ? u.address || "-"
            : role === "restaurant"
            ? u.restaurant_name || "-"
            : role === "delivery"
            ? `Status: ${u.delivery_status}`
            : "-";

        doc.fillColor(textDark).font("Times-Roman").fontSize(9);
        doc.text(fullName.trim() || "-", col1, currentY);
        doc.text(u.email || "-", col2, currentY);
        doc.text(u.phone || "-", col3, currentY);
        doc.text(details, col4, currentY, { width: 120, ellipsis: true });
        currentY += 20;
      }

      currentY += 30;
    }

    // === Footer ===
    doc.moveTo(leftMargin, pageHeight - 50).lineTo(rightMargin, pageHeight - 50).strokeColor("#9ca3af").stroke();
    doc.fontSize(9).fillColor(textLight).text("Generated automatically by the Food Court Management System", leftMargin, pageHeight - 40);

    doc.end();
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Failed to export user report", error: err.message });
  }
}
